sudo: required
language: go
go:
  - "1.12beta2"
go_import_path: github.com/xiaokangwang/AndroidLibV2ray
git:
  depth: 1
addons:
  apt:
    update: true
before_script:
- sudo ntpdate -u time.google.com
- date
- make all
- make downloadGoMobile
script:
- go test -p 1 -tags json -v github.com/xiaokangwang/AndroidLibV2ray/...
after_success:
deploy:
  provider: releases
  api_key:
    secure: "k1j9F8WhuZjotiuoV06TZEgfZfHeftlsYrvuTeZ4BiWRUOjeSoV00zg9SFOziRrHkkZRHhjUq/J/JdZCvnOH0PvKbg8VItZrc0WiPH9UfjebR4yo/7QKlmL547JSM0LZPsbebNO+3qsuE80orQgNLtpTnTAOwmm6QV5rzw3RImrCl5lhGp0syTW9fC2BNYhIHKGjsu8/iC1fugRcuK0esWIb56aVDAo86sBROBXRfDlZQVX7VHMCshY7g3JbOOgEoSyTePzcElk3g/2OejHXw6Okt2hAJWlu3Lxv8coCgmt5wOQI/6AVrXrSq/A9M/tosH3pwdNVIX+fLwm5+MoomHZb/Rc8XQbIM2j1tBghKclA4cgL/Jnoi3JX444xDtQopr4dGOpC3P9vpaLJBkuxVsl3ESD0Fy4vksib2Vz7ps8QPBWA+CjVDloin4g/Eu7vSN7igu17Wcm2Kg4Y1wNeHG6jO7clHvkSiFAfggs8RGiotzD549o2Jgax7hg9jBP9EAUDvayjhMM415VTY+kqzvibPo969L7HEuYFaBWBu0kV0pvOcSinLXJDIWSaqgKyV0Sl96bj4HXfpIh8kHH0FoDUyRoZ/xcX7l80KBiD+BWymrMphU8jvoZ0m110sB1Yh9/0yT0MMFrK/uTo3+Hc9i2EOrRPfCbkHlSgJ4G2lWA="
  file:
    - libv2ray.aar
  skip_cleanup: true
  on:
    tags: true
